### ISSUE TITLE
core/block_validator.go#calcDifficultyAtlantis: should not use hardcoded bomb delay

### ISSUE THREAD

**Issue by meowsbits** [eth-classic/go-ethereum#66]
https://github.com/eth-classic/go-ethereum/blob/development/core/block_validator.go#L326

```go
func calcDifficultyAtlantis(time uint64, parent *types.Header) *big.Int {
	bombDelayFromParent := new(big.Int).Sub(big.NewInt(3000000), big1)
	// https://github.com/ethereum/EIPs/issues/100.
	// algorithm:
	// diff = (parent_diff +
	//         (parent_diff / 2048 * max((2 if len(parent.uncles) else 1) - ((timestamp - parent.timestamp) // 9), -99))
	//        ) + 2^(periodCount - 2)

	bigTime := new(big.Int).SetUint64(time)
	bigParentTime := parent.Time

	// holds intermediate values to make the algo easier to read & audit
	x := new(big.Int)
	y := new(big.Int)
```

**Comment by soc1c** [comment]
Sorry, how does this differ from #67?

**Comment by meowsbits** [comment]
It doesn't much; this was just the preliminary result of a review that then grew larger in scope.

With that, however, the case of using "magic" values like this (aside from the contextual incorrectness reported in #67) can be seen to stand as an issue in it's own right, with hopefully few to none other such cases.

Resolution of bespoke subsequent issue will also resolve this one.
