### ISSUE TITLE
Add ethereum submodule tests to CircleCI

### ISSUE THREAD

**Issue by austinabell** [eth-classic/go-ethereum#70]
Not sure if this is necessary since it will slow down to CircleCI tests and it is assumed reviewers will test with the Ethereum submodule downloaded, but those tests are not included in the CircleCI test.

**Comment by meowsbits** [comment]
Do you mean `./tests/test[D|d]ata` tests?
https://github.com/ethereum/tests

If so, I think they should be included in the CI suite.

**Comment by GregTheGreek** [comment]
Yep, add them to the CI @austinabell

**Comment by soc1c** [comment]
Done #71
