### ISSUE TITLE
Discussion/question: squashed history

### ISSUE THREAD

**Issue by meowsbits** [eth-classic/go-ethereum#75]
The "first" commit of this repo 60d03d46f268e13cda65ba56c783035d7f0ebdce explains that it "removes a large binary file from history." A couple of questions:

- What file?
- IMO this presents a nagging security/reviewablity concern, given the size and complexity of the codebase. Has this been considered? (Especially in light of newly published binary releases)? Might there be another way to remove the file without also removing the entire history? Or a proof of an equivalent code state comparison (minus 1 file) against the original code base and history?

**Comment by soc1c** [comment]
Thanks for raising this. The squashed commit was used to reduce the size of this repository.

For the record and for transparency, the squashed commit https://github.com/eth-classic/go-ethereum/commit/60d03d46f268e13cda65ba56c783035d7f0ebdce (https://github.com/ethereumproject/go-ethereum/commit/60d03d46f268e13cda65ba56c783035d7f0ebdce) equals the last merged PR commit https://github.com/ethereumproject/go-ethereum/commit/6be652dd2f3b6c4502825fff9151539f442619f0

You can run `git diff 60d03d46f268e13cda65ba56c783035d7f0ebdce 6be652dd2f3b6c4502825fff9151539f442619f0` on ethereumproject to review the diff.

**Comment by soc1c** [comment]
Here's the diff. Just realized there actually is a diff because we used an intermediate repository before I joined the project.

https://gist.github.com/soc1c/c19bd5283be82bad1e9bc3ff6103724e

Let me know what you thnk

**Comment by meowsbits** [comment]
Yea, thanks, the reproducible diff LGTM.
