### ISSUE TITLE
Cant install following README.md

### ISSUE THREAD

**Issue by kuwukus** [eth-classic/go-ethereum#85]
Hey

Environment: 
Ubuntu 18.04 LTS
GO :  1.12.6

I'm trying to install latest release (Geth Classic v6.0.6-beta), but failing on the first step. 

**geth-user@ip-172-31-31-232:~/distro/getc$ make build**
go: github.com/huin/goupnp@v1.0.0: mkdir /home/geth-user: permission denied
go: github.com/gizak/termui@v2.3.0+incompatible: mkdir /home/geth-user: permission denied
go: github.com/eth-classic/ethash@v0.0.0-20190401191819-b3fdb17512de: mkdir /home/geth-user: permission denied
go: github.com/fatih/color@v1.7.0: mkdir /home/geth-user: permission denied
go: github.com/boltdb/bolt@v1.3.1: mkdir /home/geth-user: permission denied
go: github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc: mkdir /home/geth-user: permission denied
go: github.com/mailru/easyjson@v0.0.0-20190403194419-1ea4449da983: mkdir /home/geth-user: permission denied
go: github.com/peterh/liner@v1.1.0: mkdir /home/geth-user: permission denied
go: github.com/eth-classic/benchmark@v0.0.0-20190401191651-0f5bf26f7cd8: mkdir /home/geth-user: permission denied
go: github.com/jackpal/go-nat-pmp@v1.0.1: mkdir /home/geth-user: permission denied
go: github.com/stretchr/testify@v1.3.0: mkdir /home/geth-user: permission denied
go: github.com/spf13/afero@v1.2.2: mkdir /home/geth-user: permission denied
go: github.com/denisbrodbeck/machineid@v0.8.0: mkdir /home/geth-user: permission denied
go: github.com/rcrowley/go-metrics@v0.0.0-20181016184325-3113b8401b8a: mkdir /home/geth-user: permission denied
go: github.com/eth-classic/go-ethereum/accounts/abi/bind@v0.0.0-20190521151733-fe17e9e1e2ce: mkdir /home/geth-user: permission denied
go: github.com/hashicorp/golang-lru@v0.5.1: mkdir /home/geth-user: permission denied
go: github.com/maruel/panicparse@v1.2.0: mkdir /home/geth-user: permission denied
go: github.com/rs/cors@v0.0.0-20170727213201-7af7a1e09ba3: mkdir /home/geth-user: permission denied
go: github.com/robertkrimen/otto@v0.0.0-20180617131154-15f95af6e78d: mkdir /home/geth-user: permission denied
go: github.com/rjeczalik/notify@v0.9.1: mkdir /home/geth-user: permission denied
go: github.com/davecgh/go-spew@v1.1.1: mkdir /home/geth-user: permission denied
go: github.com/mattn/go-colorable@v0.1.2: mkdir /home/geth-user: permission denied
go: golang.org/x/sys@v0.0.0-20190419153524-e8e3143a4f4a: mkdir /home/geth-user: permission denied
go: golang.org/x/net@v0.0.0-20190419010253-1f3472d942ba: mkdir /home/geth-user: permission denied
go: golang.org/x/tools@v0.0.0-20190520220859-26647e34d3c0: mkdir /home/geth-user: permission denied
go: golang.org/x/crypto@v0.0.0-20190418165655-df01cb2cc480: mkdir /home/geth-user: permission denied
go: gopkg.in/karalabe/cookiejar.v2@v2.0.0-20150724131613-8dcd6a7f4951: mkdir /home/geth-user: permission denied
go: gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405: mkdir /home/geth-user: permission denied
go: gopkg.in/fatih/set.v0@v0.1.0: mkdir /home/geth-user: permission denied
go: gopkg.in/urfave/cli.v1@v1.17.0: mkdir /home/geth-user: permission denied
go: error loading module requirements

* Also please mention required version of Go in README.md. Default version on ubuntu is 1.10 and that was failing with other error message (paths related).,
I could run to next error after manually installing 1.12, lost some time trying to fix them and finally just to understand that version isn't latest.

Thanks

**Comment by soc1c** [comment]
`permission denied` ?
