### ISSUE TITLE
Stable version before Atlantis hard fork

### ISSUE THREAD

**Issue by fish-sammy** [eth-classic/go-ethereum#88]
This is more of a question than an issue. Are you guys going to release a stable version before the Atlantis hard fork on mainnet, and if so, is there any schedule of when should I expect it to come out?

**Comment by GregTheGreek** [comment]
Please use GitHub.com/etclabscore/go-ethereum for active discussions.

**Comment by soc1c** [comment]
@sammy1991106 yes, please subscribe to our releases
